Repository celestiaorg/rsmt2d, pull requests merged in 2022-08, with the labels that each got.

#102 testing: immutability constraints on Row, Cell, GetCell, and SetCell
  datasquare_test.go
  extendeddatasquare.go
  extendeddatasquare_test.go
Labels: testing

#98 Exporting `dataSquare.flattened`
  datasquare.go
  datasquare_test.go
  extendeddatacrossword_test.go
  extendeddatasquare.go
Labels: enhancement

#106 Upgrade to Go 1.18
  .github/workflows/ci.yml
  go.mod
Labels: breaking
