Repository celestiaorg/rsmt2d, pull requests merged in 2022-06, with the labels that each got.

#92 Export `SetCell` and `GetCell`.
  datasquare.go
  extendeddatacrossword.go
  extendeddatacrossword_test.go
Labels: enhancement

#93 Cache codec and tree func.
  extendeddatacrossword.go
  extendeddatacrossword_test.go
  extendeddatasquare.go
  rsmt2d_test.go
Labels: enhancement, breaking

#94 Update readme to reflect removal of codec and tree
  README.md
Labels: documentation

#95 Clarifying Encode's return value in comment
  codecs.go
Labels: documentation
