Repository celestiaorg/rsmt2d, pull requests merged in 2023-07, with the labels that each got.

#206 docs: fix new codec in example
  README.md
Labels: documentation

#207 docs: clarify shares inside ErrByzantineData
  extendeddatacrossword.go
Labels: documentation

#203 test: do not perform input validation in `setCell`
  datasquare.go
  datasquare_test.go
  extendeddatacrossword.go
Labels: bug, testing

#208 feat!: enable golangci-lint
  .github/workflows/lint.yml
  .golangci.yml
  README.md
  datasquare.go
  datasquare_test.go
  extendeddatacrossword.go
  extendeddatacrossword_test.go
  extendeddatasquare.go
  extendeddatasquare_test.go
  leopard.go
  rsmt2d_test.go
  tree.go
Labels: breaking

#190 fix: populate shares in `ErrByzantineData`
  extendeddatacrossword.go
  extendeddatacrossword_test.go
Labels: bug

#239 test: add test case based on celestia-node usage
  rsmt2d_test.go
Labels: enhancement, testing

#240 docs: clarify rowRoots to Repair
  extendeddatacrossword.go
Labels: documentation

#242 feat: extends error handling to detect byzantine data and unordered shares in tree construction
  datasquare.go
  extendeddatacrossword.go
  extendeddatacrossword_test.go
  extendeddatasquare_test.go
  go.mod
  go.sum
  nmtwrapper_test.go
Labels: enhancement

#250 docs: informal systems audit PDF
  README.md
  audit/informal-systems.pdf
Labels: audit
